"""
Affixator module for conlang word generator.

Defines a ConlangAffixator class that applies affixation rules to words
generated by the word generator.  It reads affixation rules from a separate
file and uses the existing ConlangData class to handle grapheme tokenization
and character classification.

The affixation process considers the final character of the root word and
the initial character of the affix to determine the appropriate inflection
rules to apply based on the phonological rules built into the language
definition.

The affixator supports both prefixing and suffixing affixes, and can handle
inflection rules specific to verbs, nouns, and other word types as defined
in the affixation rules file.

The affixator may be run interactively.

Note: If either of the rule files for affixation or inflection contain rules
that include phonemes not defined in the main language data file, then
unexpected behavior may occur during affixation.  This is a pain point that
I am actively considering how to resolve.

Another Note: If your conlang uses non-concatenative morphology (e.g.,
root-and-pattern morphology as in Semitic languages), then this affixator will
not work for you.  This tool only supports concatenative morphology (i.e.,
prefixes and suffixes).

Still Another Note: Error-handling is somewhat minimal at present.  If an error
occurs during affixation (e.g., due to undefined phonemes in the affixation
rules), then an error message will be printed to stderr and the affixation
will be skipped for that particular affix.  The program will continue running
after logging the error.  If it breaks, you may keep the pieces.

Usage: python affixator.py -L <language> <word> [-R]
    * -L <language>: The conlang to use (default: keregafa)
    * word: The word to affixate
    * -R: Output raw words instead of JSON (useful for piping into other
      tools such as `pbcopy`)

Author: William Ellison <tnwae@pm.me>
License: WTFPLv2 (http://www.wtfpl.net/txt/copying/)
Web: https://github.com/tnwae/wordgen
"""

#!/usr/bin/env python3

import json
import sys
import re
from typing import Dict
import conlang_utils as cu


class ConlangAffixator:
    """Conlang affixator class.

    See the top of this file for a description of what this class does.
    """

    def __init__(self,
                 affix_ruletab: str,
                 datatab: str,
                 inflection_ruletab: str):
        """Create a new affixator object.

        :param affix_ruletab: The affix rule table, named
        `${LANG}_affixes.json`

        :param datatab: The data table, named `${LANG}.json`

        :param inflection_ruletab: The inflection rule table, named
            `${LANG}_inflections.json`

        """
        self.conlang_data = cu.ConlangData(datatab)

        # Load the affixation rules from disk.
        try:
            with open(affix_ruletab, "r") as fp:
                raw = json.load(fp)
                self.suffixing_rules = self.conlang_data.suffix_rules
                self.prefixing_rules = self.conlang_data.prefix_rules
                self.affixes = raw["affixes"]
                self.basic_attributes = raw["basicAttributes"]
                self.tunings = raw.get("tunings") or None
                self.generic_decompilation = self.conlang_data.basic_attributes.get("decompileCharsGenerically", True)
        except FileNotFoundError as ex:
            print(ex)
            sys.exit(1)

        # Load the language inflection rules from disk.
        try:
            with open(inflection_ruletab, "r") as fp:
                raw = json.load(fp)
                self.declension_templates = raw["cases"]
                self.tense_templates = raw["tenses"]
                self.basic_attributes.update(raw["basicAttributes"])
        except FileNotFoundError as ex:
            print(ex)
            sys.exit(1)

        # Define the mapping for inflection actions.  If you want to
        # add new inflection actions, then place the mappings here
        # and define the corresponding method in the ConlangData class
        # (conlang_utils.py).
        self.INFLECTION_ACTIONS = {
            "deleteLastChar": self.conlang_data.delete_last_char,
            "appendLastVowel": self.conlang_data.append_last_vowel,
            "appendLastConsonant": self.conlang_data.append_last_consonant,
            "doNothing": self.conlang_data.do_nothing_for_inflection
        }

    def _inflect_suffix(self, word: str, suffix: str) -> str:
        """
        Add a suffix to a word.

        :param word: The word to add the suffix to.
        :param suffix: The suffix to add.  If "@", no suffix is added.
        :return: The inflected word.
        """
        if suffix == "@":
            return word

        # Tokenize the word and suffix to determine the appropriate inflection rule.
        # This is based on the final character class of the word and the initial
        # character class of the suffix, as defined in the affixation rules.
        word_tokens = self.conlang_data.tokenize_word(word)
        suffix_tokens = self.conlang_data.tokenize_word(suffix)
        final_token_class = self.conlang_data.get_char_class(word_tokens[-1], self.generic_decompilation)
        case_ending_class = self.conlang_data.get_char_class(suffix_tokens[0], self.generic_decompilation)

        # Retrieve and apply the inflection rule.
        rule = self.suffixing_rules[final_token_class][case_ending_class]
        root_tokens = self.INFLECTION_ACTIONS[rule](word_tokens)
        final_word = root_tokens + suffix_tokens
        return self.conlang_data.detokenize_word(final_word)

    def _inflect_prefix(self, word: str, prefix: str) -> str:
        """
        Add a prefix to a word.

        :param word: The word to add the prefix to.
        :param prefix: The prefix to add.  If "@", no prefix is added.
        :return: The inflected word.
        """
        if prefix == "@":
            return word

        # Tokenize the word and prefix to determine the appropriate inflection rule.
        # This is based on the initial character class of the word and the final
        # character class of the prefix, as defined in the affixation rules.
        word_tokens = self.conlang_data.tokenize_word(word)
        prefix_tokens = self.conlang_data.tokenize_word(prefix)
        first_token_class = self.conlang_data.get_char_class(word_tokens[0], self.generic_decompilation)
        prefix_ending_class = self.conlang_data.get_char_class(prefix_tokens[-1], self.generic_decompilation)

        # Retrieve and apply the inflection rule.
        rule = self.prefixing_rules[prefix_ending_class][first_token_class]
        inflected_tokens = self.INFLECTION_ACTIONS[rule](prefix_tokens)
        final_word = inflected_tokens + word_tokens
        return self.conlang_data.detokenize_word(final_word)

    def affixate(self, word: str) -> Dict[str, str]:
        """
        Generate the inflected forms of a word.

        :param word: The word to inflect.
        :return: A dictionary of inflected forms keyed on the name of the form.
        """
        verb_affixes = self.basic_attributes["verbAffixes"]
        verb_class = ""
        word_is_a_verb = False

        if self.basic_attributes.get("declensionMethod", "suffix") == "suffix":
            regexp = r"{what}$"
        else:
            regexp = r"^{what}"

        # Determine if the word is a verb by checking its verbal affix against
        # the verb endings defined for the language.
        #
        # Note that this is a simplistic approach that may not work for all
        # languages.  A more robust approach would involve part-of-speech
        # tagging or morphological analysis, but that is beyond the scope of
        # this tool and is likely to remain so for the foreseeable future.
        for verb_affix in verb_affixes:
            if re.findall(regexp.format(what=verb_affix), word):
                verb_class = str(verb_affix)
                word_is_a_verb = True
                break
        
        if word_is_a_verb:
            return self._affixate_verb(word, verb_class)
        
        else:
            return self._affixate_noun(word)
    
    def _affixate_noun(self, word: str) -> Dict[str, str]:
        result = dict()

        if self.basic_attributes.get("declensionMethod", "suffix") == "suffix":
            inflect = self._inflect_suffix
        else:
            inflect = self._inflect_prefix

        # Decline the noun for each case defined in the inflection rules.
        for case, inflection in self.declension_templates.items():
            if case == "_className":
                continue

            affixed_word = inflect(word, inflection)
            result[case] = affixed_word

        # Apply each affixation rule to the word as appropriate.
        for affix, rules in self.affixes.items():
            if affix == "_className":
                continue

            name = affix
            affixed_word = None
            prefix = rules.get("prefix", None)
            suffix = rules.get("suffix", None)

            # Retrieve only affixation rules that apply to nouns.
            affix_applies_to_noun = any(["N-N" in name, "N-Adj" in name, "N-V" in name])

            if affix_applies_to_noun:
                if prefix:
                    affixed_word = self._inflect_prefix(word, prefix)
                if suffix:
                    affixed_word = self._inflect_suffix(word, suffix)
                result[name] = affixed_word

        return result

    def _affixate_verb(self, word: str, verb_class: str) -> Dict[str, str]:
        result = dict()
        tense_templates = self.tense_templates.get(verb_class, {})

        if self.basic_attributes.get("conjugationMethod", "suffix") == "suffix":
            inflect = self._inflect_suffix
        else:
            inflect = self._inflect_prefix

        # Apply any tunings that affect the functionaity of the affixator.
        verb_form_for_suffixes = None
        if self.tunings:
            verb_form_for_suffixes = self.tunings.get("applySuffixToVerbForm", None)
        
        # Conjugate the verb for each tense defined in the inflection rules.
        for tense, inflection in tense_templates.items():
            if tense == "_className":
                continue

            affixed_word = inflect(word[:-len(verb_class)], inflection)
            result[tense] = affixed_word
        
        # Apply each affixation rule to the word as appropriate.
        for affix, rules in self.affixes.items():
            if affix == "_className":
                continue

            name = affix
            affixed_word = None
            affix_applies_to_verb = False
            prefix = rules.get("prefix", None)
            suffix = rules.get("suffix", None)

            # Retrieve only affixation rules that apply to verbs.
            affix_applies_to_verb = any(["V-V" in name, "V-Adj" in name, "V-N" in name])

            try:
                if affix_applies_to_verb:
                    if prefix:
                        affixed_word = self._inflect_prefix(word, prefix)
                    if suffix:
                        if verb_form_for_suffixes and verb_form_for_suffixes in tense_templates:
                            affixed_word = self._inflect_suffix(
                                self._inflect_suffix(
                                        word[:-len(verb_class)],
                                        tense_templates[verb_form_for_suffixes]
                                    ),
                                suffix
                            )
                        else:
                            affixed_word = self._inflect_suffix(
                                word[:-len(verb_class)],
                                suffix
                            )
                    result[name] = affixed_word
            except Exception as ex:
                print(f"Error applying affix: {ex}", file=sys.stderr)
                print("Suspect that the affixation table includes an undefined phoneme.", file=sys.stderr)
                print(f"\tRule: {affix}", file=sys.stderr)
                print(f"\tWord: {word}", file=sys.stderr)
                print(f"\tPrefix: {prefix}", file=sys.stderr)
                print(f"\tSuffix: {suffix}", file=sys.stderr)
                print("This will be excluded from the output.  Continuing.", file=sys.stderr)

        return result


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser("affixator")
    parser.add_argument("-L",
                        "--language",
                        help="language (default: keregafa)",
                        type=str,
                        default="keregafa")
    parser.add_argument("word", help="word to inflect", type=str)
    parser.add_argument("-R",
                        "--raw-output",
                        help="output raw words",
                        action='store_true')
    args = parser.parse_args()

    affixes_ruletab = f"./{args.language}_affixes.json"
    conlang_datatab = f"./{args.language}.json"
    inflection_ruletab = f"./{args.language}_inflections.json"

    ci = ConlangAffixator(affixes_ruletab, conlang_datatab, inflection_ruletab)
    inflected_words = ci.affixate(args.word)

    if args.raw_output:
        for _, word in inflected_words.items():
            print(word)
    else:
        print(json.dumps(inflected_words, indent=4))
